language: node_js
node_js:
- '0.11'
deploy:
  provider: npm
  email: mail@jonasw.de
  api_key:
    secure: kFKsQom7yeOo/+CfCxtCubX2VIPIxhL3c1WXxo5EV6zcumTteyMREtv4OhHzMgUW5QqEJpxMPEodVeQzsmtjrWdnW7pkKCl5CK5oJ1N13SVsjShzE7h/SwuF5Mz8C4ZRzn99y3mPL2GhZM9KDVnyw/6X3iMi9vPIGP5at6kK8NM=
  on:
    branch: master
    repo: thriqon/random-word-generator

before_deploy:
  - mkdir -p .git/logs/refs/stash
